# frozen_string_literal: true

# Template Name: Jayroh Kickofftemplate
# Author: Joel Oliveira
# Author URI: https://joeloliveira.com
# Instructions: $ rails new myapp -m ~/.dotfiles/tag-ruby/rails_template/template.rb

def source_paths
  [__dir__]
end

def remove_commented_lines(file)
  file_content = File.readlines(file)
  filtered_content = file_content.reject { |line| line.match?(/^\s*#/) }

  File.open(file, 'w') do |file|
    file.puts filtered_content
  end
end

def create_files
  create_file 'Procfile', <<~PROCFILE
    web: bin/rails s -b 0.0.0.0
    vite: bin/vite dev
    rubocop: bin/rubocop --start-server --no-detach
  PROCFILE
end

def remove_gemfile_groups
  gemfile_content = File.read('Gemfile')
  cleaned = gemfile_content.each_line.with_object([]) do |line, result|
    @inside_group ||= false
    if line.strip.start_with?('group ') && line.strip.end_with?('do')
      @inside_group = true
    elsif @inside_group && line.strip == 'end'
      @inside_group = false
    elsif !@inside_group
      result << line
    end
  end.join
  File.write('Gemfile', cleaned)
end

def set_up_gemfile
  insert_into_file 'Gemfile',
                   "\n\nruby file: '.tool-versions'",
                   after: 'source "https://rubygems.org"'
  remove_commented_lines 'Gemfile'
  remove_gemfile_groups

  gem 'faker', require: false
  gem 'friendly_id'
  gem 'image_processing'
  gem 'vite_rails'
  gem 'solid_errors'

  gem_group :development, :test do
    gem 'brakeman', require: false
    gem 'bundler-audit', require: false
    gem 'dotenv'
    gem 'pry-byebug'
    gem 'pry-rails'
    gem 'rspec-rails'
    gem 'rubocop', require: false
    gem 'rubocop-capybara', require: false
    gem 'rubocop-factory_bot', require: false
    gem 'rubocop-performance', require: false
    gem 'rubocop-rails', require: false
    gem 'rubocop-rspec', require: false
    gem 'rubocop-rspec_rails', require: false
  end

  gem_group :development do
    gem 'database_consistency', require: false
    gem 'i18n-tasks'
    gem 'lefthook'
    gem 'overmind'
    gem 'web-console'
  end

  gem_group :test do
    gem 'cuprite'
    gem 'factory_bot_rails'
    gem 'generator_spec'
    gem 'shoulda-matchers'
  end
end

def copy_files
  copy_file '.rubocop.yml', force: true
  copy_file 'Rakefile', force: true
  copy_file 'lefthook.yml', force: true
  copy_file 'bin/setup', force: true
  copy_file '.env.sample', force: true

  directory 'app', force: true
  directory 'config', force: true
  directory 'spec', force: true

  ignore_tt do
    directory 'lib', force: true
  end
end

def ignore_tt
  Thor::TEMPLATE_EXTNAME.concat '_no_match' # => .tt_no_match
  yield
ensure
  Thor::TEMPLATE_EXTNAME.chomp! '_no_match' # => .tt
end

def install_binstubs
  binstubs = %w[
    lefthook
    overmind
    rspec-core
    rubocop
    vite_rails
  ]
  run "bundle binstubs #{binstubs.join(' ')}"
end

def run_generators
  generate 'friendly_id'
  generate 'rspec:install'
end

def add_npm_dependencies
  run 'npm i -D @hotwired/turbo heroicons postcss prettier stimulus-vite-helpers vite vite-plugin-rails vite-plugin-ruby'

  run 'npm i @hotwired/stimulus @hotwired/turbo-rails @rails/actioncable @rails/activestorage @rails/request.js @tailwindcss/aspect-ratio @tailwindcss/typography @tailwindcss/vite autoprefixer daisyui stimulus-vite-helpers tailwind-scrollbar tailwindcss tailwindcss-displaymodes'

  run 'vite install'
end

def set_up_database
  generate 'migration enable_uuid_extension'
  generator_file = Dir['db/migrate/*_enable_uuid_extension.rb'].first
  append_to_file generator_file, "\nenable_extension 'pgcrypto'", after: 'def change'
  remove_commented_lines 'config/database.yml'
end

def set_up_turbo
  rails_command 'turbo:install'
end

def update_app_config
  run 'i18n-tasks remove-unused -y'

  insert_into_file 'config/application.rb', after: /.*config.load_defaults.*$/ do
    <<~APP_CONFIG
      \n
      config.generators do |g|
        g.factory_bot dir: 'spec/factories'
        g.helper false
        g.orm :active_record, primary_key_type: :uuid
        g.request_specs false
        g.routing_specs false
        g.test_framework :rspec
        g.view_specs false
      end

      config.active_job.queue_adapter = :async

      # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
      config.generators.apply_rubocop_autocorrect_after_generate!
    APP_CONFIG
  end
end

def update_routes
  route "root to: 'home#index'"
end

# Main setup
source_paths
create_files
set_up_gemfile

after_bundle do
  say '⚡Adding npm dependencies ...', :yellow
  add_npm_dependencies

  say '⚡Running generators ...', :yellow
  run_generators

  say '⚡Setting up database ...', :yellow
  set_up_database

  say '⚡Setting up turbo ...', :yellow
  set_up_turbo

  say '⚡Copying over files ...', :yellow
  copy_files

  say '⚡Installing binstubs ...', :yellow
  install_binstubs

  say '⚡Updating app config file ...', :yellow
  update_app_config

  say '⚡Updating routes ...', :yellow
  update_routes

  # Migrate
  say '⚡Migrating database...', :yellow
  rails_command 'db:create'
  rails_command 'db:migrate'

  # Install lefthook git hooks
  say '⚡Installing lefthook git hooks...', :yellow
  run 'bin/lefthook install'

  # Rubocop all the things
  say '⚡Running rubocop ...', :yellow
  rails_command 'rubocop', abort_on_failure: false

  # Git
  say '⚡Initializing git...', :yellow
  copy_file '.gitignore', force: true
  git :init
  git add: '.'
  git commit: %( -m "Initial commit" )
  run 'mkdir -p .git/safe'

  say 'Kickoff app successfully created! 👍'..., :green
end
