-- Tab navigation
vim.keymap.set('n', '<leader>tl', ':tabnext<CR>', { noremap = true })
vim.keymap.set('n', '<leader>th', ':tabprevious<CR>', { noremap = true })
vim.keymap.set('n', '<leader>te', ':tabedit<CR>:e<space>', { noremap = true })
vim.keymap.set('n', '<leader>1', '1gt', { noremap = true })
vim.keymap.set('n', '<leader>2', '2gt', { noremap = true })
vim.keymap.set('n', '<leader>3', '3gt', { noremap = true })
vim.keymap.set('n', '<leader>4', '4gt', { noremap = true })
vim.keymap.set('n', '<leader>5', '5gt', { noremap = true })
vim.keymap.set('n', '<leader>6', '6gt', { noremap = true })
vim.keymap.set('n', '<leader>7', '7gt', { noremap = true })
vim.keymap.set('n', '<leader>8', '8gt', { noremap = true })
vim.keymap.set('n', '<leader>9', '9gt', { noremap = true })
vim.keymap.set('n', '<leader>0', '10gt', { noremap = true })